export default{
    path:"/search",
    component:()=>import("@/views/search/search"),
    children:[
        {
            path:"detail/:keywords/songs",
            component:()=>import("@/views/search/indexComponents/Songs")
        },
        {
            path:"detail/:keywords/video",
            component:()=>import("@/views/search/indexComponents/Video")
        },
        {
            path:"detail/:keywords/album",
            component:()=>import("@/views/search/indexComponents/Album")
        },
        {
            path:"detail/:keywords/playlist",
            component:()=>import("@/views/search/indexComponents/Playlist")
        },
        {
            path:"detail/:keywords/singer",
            component:()=>import("@/views/search/indexComponents/Singer")
        },
        {
            path:"detail/:keywords",
            redirect:"detail/:keywords/songs"
        }
    ]
}